# Decoding a neural network from a JSON file to Python, then encoding the hessian from laplace.py to a CSV (regression)

- Step 1: Read the dataset
- Step 2: Initialize model
- Step 3: Read the weights and biases from the JSON file, then load them into the previously initialized model
- Step 4: Generate the hessians and write them to CSV files

In [22]:
# imports
from laplace import Laplace

import numpy as np
import pandas as pd
import torch

import json

import torch.nn as nn
from torch.utils.data import TensorDataset, DataLoader

torch.manual_seed(43)

### Step 1: Read the dataset

In [23]:
# Import data from csv

# Load data from CSV file using pandas
df = pd.read_csv('data_regression.csv')

# Split the dataframe into x and y tensors
data = torch.from_numpy(df[['xs', 'y']].to_numpy()).to(torch.float32)
x = torch.from_numpy(df['xs'].to_numpy()).to(torch.float32)
y = torch.from_numpy(df['y'].to_numpy()).to(torch.float32)

### Step 2: Initialize model

In [24]:
# Init model

n_hidden = 10
D = 1
out_dim = 1 
model = nn.Sequential(
    nn.Linear(D, n_hidden),
    nn.Tanh(),
    nn.Linear(n_hidden, out_dim)
)

loss_fn = nn.CrossEntropyLoss()

### Step 3: Read the weights and biases from the JSON file, then load them into the previously initialized model

In [25]:
with open('nn_regression.json') as fin:
    nn_json_str = fin.read()
    nn_json = json.loads(nn_json_str)

nn_json

[{'bias': [-0.42261407,
   -0.21227753,
   -0.0096151605,
   -0.7529069,
   1.3016218,
   3.116596,
   -2.1422381,
   -1.2806743,
   0.78418183,
   -1.3360132],
  'weight': [[-0.55855876,
    0.2368329,
    0.7279194,
    1.1712134,
    -0.2849682,
    -0.82284534,
    0.76305974,
    0.28283465,
    -0.24539436,
    0.6470228]]},
 {'bias': [0.13576016],
  'weight': [[-0.27233723],
   [0.7866149],
   [0.26231468],
   [0.16347119],
   [-1.6750962],
   [1.7097319],
   [-1.3647312],
   [1.6296383],
   [-1.1626163],
   [-0.75578994]]}]

In [26]:
assert len(model.state_dict()) == 2 * len(nn_json)
iter_states = iter(model.state_dict())

# for layer in model.state_dict():
#     print(layer)
for layer_read in nn_json:
    state_w = next(iter_states)
    state_b = next(iter_states)
    tensor_w = torch.tensor(layer_read['weight']).T
    tensor_b = torch.tensor(layer_read['bias']).T
    model.state_dict()[state_w].data.copy_(tensor_w)
    model.state_dict()[state_b].data.copy_(tensor_b)


In [27]:
for val in model.state_dict().values():
    display(val)

tensor([[-5.585588e-01],
        [2.368329e-01],
        [7.279194e-01],
        [1.171213e+00],
        [-2.849682e-01],
        [-8.228453e-01],
        [7.630597e-01],
        [2.828346e-01],
        [-2.453944e-01],
        [6.470228e-01]])

tensor([-4.226141e-01, -2.122775e-01, -9.615161e-03, -7.529069e-01, 1.301622e+00, 3.116596e+00,
        -2.142238e+00, -1.280674e+00, 7.841818e-01, -1.336013e+00])

tensor([[-2.723372e-01, 7.866149e-01, 2.623147e-01, 1.634712e-01, -1.675096e+00, 1.709732e+00,
         -1.364731e+00, 1.629638e+00, -1.162616e+00, -7.557899e-01]])

tensor([1.357602e-01])

### Step 4: Generate the hessians and write them to CSV files

In [28]:
# we use the unsqueeze() method with the argument 1 to add an extra dimension
# this extra dimension converts each value into an array of its own
X = x.unsqueeze(1)

In [29]:
la = Laplace(model, 'regression',
             subset_of_weights='all',
             hessian_structure='full')

la.fit(DataLoader(TensorDataset(X, y), batch_size=1))

hessian = la.H
array = hessian.numpy()
np.savetxt('hessian_regression_all_full_ggn.csv', array, delimiter=',')

c:\Users\adeli\OneDrive\Desktop\facultate\2nd year\Q4 - Software Project\LaplaceRedux.jl\myenv\lib\site-packages\torch\nn\modules\loss.py:536: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


In [30]:
la = Laplace(model, 'regression',
             subset_of_weights='last_layer',
             hessian_structure='full')

la.fit(DataLoader(TensorDataset(X, y), batch_size=1))

hessian = la.H
array = hessian.numpy()
np.savetxt('hessian_regression_ll_full_ggn.csv', array, delimiter=',')

In [31]:
la = Laplace(model, 'regression',
             subset_of_weights='subnetwork',
             subnetwork_indices = torch.LongTensor([1, 3, 5, 6, 7, 9]),
             hessian_structure='full')

la.fit(DataLoader(TensorDataset(X, y), batch_size=1))

hessian = la.H
array = hessian.numpy()
np.savetxt('hessian_regression_subnet_full_ggn.csv', array, delimiter=',')